### ISSUE TITLE
Assignment 3-3 - Constructors

### ISSUE THREAD

**Issue by ambethia** [basquith16/Assignments#10]
# Constructors

## Description
Copy the included [`constructors.js`](https://raw.githubusercontent.com/tiy-tpa-js-q3-2015/notes/master/week-3/constructors.js) to a new project. Add an `index.html` that includes it. Answer all the questions and upload to __gh-pages__.

Keep in mind in the examples in `constructors.js` I need to be able to test them in __gh-pages__ on the console. Also make sure there are no javascript errors and check your code in [js hint](http://jshint.com/). Finally make sure it is formatted/indented correctly. Code is in place that validates each answer. It will currently say: `Assertion failed` for each question. Once you answer the question correctly that will go away. Use this to check your work.

### Learning Objectives

After completing this assignment, you should…

* Understand how constructor functions work in JavaScript

### Performance Objectives

After completing this assignment, you be able to effectively use

* [Github Pages](https://pages.github.com/)

### Deliverables

* A repo containing at least:
  - the `constructors.js` file
  - a branch called `gh-pages`

### Requirements

* No JSHint warnings or errors

## Additional Resources

* [Object.prototype.constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor)
* [Working with objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects)

**Comment by basquith16** [comment]
![screen shot 2015-09-10 at 8 39 57 am](https://cloud.githubusercontent.com/assets/11594023/9788431/bc50d5e2-5797-11e5-9a56-122a957d6b56.png)

http://basquith16.github.io/Wed-9.8-Homework/

I am not confident that I did anything correct with the problems. As you can tell, I couldn't get it to load to gh-pages correctly.

**Comment by ambethia** [comment]
![Awesome Work!](http://media.giphy.com/media/OCv3v7ORwJRSw/200w_d.gif)
