### ISSUE TITLE
Assignment 4-1 - jQuery TODOs

### ISSUE THREAD

**Issue by ambethia** [basquith16/Assignments#12]
### Description

Recreate the quintessential "TODO" list:

![](https://dl.dropboxusercontent.com/u/4024808/tiy/todos.png)

### Objectives

* Understand jQuery and DOM manipulation
* Understand HTML forms, inputs and their JS events

### Deliverables

- [x] a link to your source files, can be a Github repo or a Codepen.
- [x] a working, publicly visible website with a public URL (i.e. on Github Pages, or Codepen).

## Explorer Mode

- [x] Use jQuery
- [x] A form with a text input field to enter a task
- [x] When a task is added, append it to a list of tasks.
- [x] Tasks should be able to be marked as completed, this should change their visual appearance.

## Adventure Mode

- [ ] Add a filter (or tabs) to the TODO list to only show incomplete or completed items.

## Additional Resources & Documenation

- [MDN: HTML Forms Guide](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Forms)
- [jQuery API Docs](http://api.jquery.com)
- [jQuery Learning Center](https://learn.jquery.com)

**Comment by basquith16** [comment]
http://basquith16.github.io/ToDoList/
https://github.com/basquith16/ToDoList/tree/gh-pages

**Comment by basquith16** [comment]
Hey Jason,

  I was wondering if you could sit with me tomorrow afternoon for a bit and go over my tictactoe. I've created a wide variety of issues for myself that I can’t seem to solve. I am too stubborn to bail on my vision, so I’ve just been in limbo for the last several days.

  Also, I apologize for missing class. I was up until 5am fri, 5am, Sat, and then 6:30am on Sunday. I crashed hard and was passed out until 4:30p. 

Brian

**Comment by ambethia** [comment]
@basquith16 Did we ever get a chance to go over this? Sorry I'm just seeing the message now.

**Comment by ambethia** [comment]
![Awesome Work!](http://media.giphy.com/media/QPHDRnGgHqGTC/200w_d.gif)

**Comment by basquith16** [comment]
It’s okay. I think that afternoon you were installing the ethernet cables, so I sat down with Gavin and he helped me figure it out.

I may need to bend your ear on Monday for awhile though. I’m going to do my damnedest to figure out Backbone/Ajax/This by then, but we’ll see how it goes. 

I get the basic concept (I think), that a Backbone Model acts like an object prototype, but it actually contains different objects. The BackboneView is what uses Get/Push/Fetch to send and receive information from the server. Backbone Collections would be if you had other Models that contained the same objects/properties, like multiple Facebook accounts, news articles, etc. Kinda sorta? 

The biggest problem I have is that I get lost in the process. I feel like there’s so may instances of ‘this’ and I don’t understand what they are referring to. Then I feel like I have finally it written out correctly, but nothing works. I truly stayed up every night until 3-3:30 last week trying to get it. I probably wrote 2000 lines of code or more in attempts to get it right. I’m just hoping for the lightbulb to come on before I fall too far behind. I am really bummed that I missed the study sessions today.


B
